name: Deploy CI
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: development
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://vixiees.com/android-chrome-192x192.png
          SLACK_MESSAGE: 'A new deployment is being sent to production'
          SLACK_TITLE: 'New deployment coming! :rocket:'
          SLACK_USERNAME: 'GitHub Actions 🤖'
          SLACK_FOOTER: # Commit ${{ steps.vars.outputs.sha_short }}
          MSG_MINIMAL: commit
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}